export const mainScreenArticle = {
  title: "Top 10 Champions With The Most Skins in League of Legends",
  category: "League of Legends",
  description: "Latest articles from the blog",
  keywords: "latest articles, latest blog posts",
  url: "https://www.james-mcguigan.com/latest-articles",
  image: "/src/assets/LOLCover.jpg",
};

export const popularArticlesList = [
  {
    uid: 1001,
    title: "Top 10 Champions With The Most Skins in League of Legends",
    category: "League of Legends",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/LOLCover.jpg",
  },
  {
    uid: 1002,
    title: "Top 7 Most Broken Top Laners in Volarant",
    category: "Volarant",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/VALORANT.png",
  },
  {
    uid: 1003,
    title: "How to Slow Push and freeze Lane in GTA V",
    category: "GTA V",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/gta.jpg",
  },
  {
    uid: 1004,
    title: "Top 10 Champions With The Most Skins in League of Legends",
    category: "League of Legends",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/LOLCover.jpg",
  },
  {
    uid: 1005,
    title: "Top 7 Most Broken Top Laners in Volarant",
    category: "Volarant",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/VALORANT.png",
  },
  {
    uid: 1006,
    title: "How to Slow Push and freeze Lane in GTA V",
    category: "GTA V",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/gta.jpg",
  },
  {
    uid: 1007,
    title: "Top 7 Most Broken Top Laners in Volarant",
    category: "Volarant",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/VALORANT.png",
  },
  {
    uid: 1012,
    title: "How to Slow Push and freeze Lane in GTA V",
    category: "GTA V",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/gta.jpg",
  },
  {
    uid: 1014,
    title: "Top 10 Champions With The Most Skins in League of Legends",
    category: "League of Legends",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/LOLCover.jpg",
  },
  {
    uid: 201,
    title: "Top 7 Most Broken Top Laners in Volarant",
    category: "Volarant",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/VALORANT.png",
  },
  {
    uid: 1201,
    title: "How to Slow Push and freeze Lane in GTA V",
    category: "GTA V",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/gta.jpg",
  },
];

export const featuredArticlesList = [
  {
    uid: 1001,
    title: "Top 10 Champions With The Most Skins in League of Legends",
    category: "League of Legends",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/LOLCover.jpg",
  },
  {
    uid: 1002,
    title: "Top 7 Most Broken Top Laners in Volarant",
    category: "Volarant",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/VALORANT.png",
  },
  {
    uid: 1003,
    title: "How to Slow Push and freeze Lane in GTA V",
    category: "GTA V",
    description: "Latest articles from the blog",
    keywords: "latest articles, latest blog posts",
    url: "https://www.james-mcguigan.com/latest-articles",
    image: "/src/assets/gta.jpg",
  },
];
